from routes.auth import auth_bp
from routes.dashboard import dashboard_bp
from routes.cash import cash_bp
from routes.sales import sales_bp
from routes.journal import journal_bp
from routes.ar import ar_bp
from routes.ap import ap_bp
from routes.inventory import inventory_bp
from routes.insights import insights_bp
from routes.admin import admin_bp
from routes.plan import plan_bp
from routes.api import api_bp