from routes.auth import auth_bp
from routes.dashboard import dashboard_bp
from routes.cash import cash_bp
from routes.sales import sales_bp
from routes.journal import journal_bp
from routes.ar import ar_bp
from routes.ap import ap_bp
from routes.inventory import inventory_bp
from routes.insights import insights_bp
from routes.admin import admin_bp
from routes.plan import plan_bp
from routes.api import api_bp
from routes.quick_tap import quick_tap_bp
from .all_transactions import all_transactions_bp
from .import_data import import_bp
from .orders import orders_bp
from .quotations import quotations_bp
from .budgets import budgets_bp
from .projects import projects_bp
from .timecards import timecards_bp
from .assets import assets_bp
from .reports import reports_bp
from .branches import branches_bp
from .payments import payments_bp
from .recurring import recurring_bp
from .bank_reconciliation import bank_rec_bp
from .fiscal_year import fiscal_bp
from .tax import tax_bp
from .currencies import currencies_bp
from .permissions import permissions_bp
from .planner import planner_bp
from routes.tasks import tasks_bp